--Admin, 123456789, SQL Login Creds
CREATE DATABASE JavaProject
USE JavaProject

CREATE TABLE UserRoles
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	RoleName NVARCHAR(50) NOT NULL
)

CREATE TABLE Movie
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Title NVARCHAR(250) NOT NULL,
	PubDate DATETIME NOT NULL,
	MovieDescription NVARCHAR(MAX) NOT NULL,
	OrigTitle NVARCHAR(250) NOT NULL,
	Duration INT NOT NULL,
	MovieGenreId INT FOREIGN KEY REFERENCES MovieGenre(Id),
	MoviePicturePath NVARCHAR(MAX) NULL,
	MovieLink NVARCHAR(MAX) NULL,
	MovieBegin DATETIME NULL
)

SELECT GETDATE()

CREATE PROC selectMovies
AS
BEGIN
	SELECT * FROM Movie
END

CREATE PROC selectMovieById
	@movieId INT
AS
BEGIN
	SELECT * FROM Movie WHERE Id = @movieId
END

CREATE TABLE MovieGenre
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	GenreName NVARCHAR(50) NOT NULL
)

CREATE TABLE Actor
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	FirstName NVARCHAR(25) NOT NULL,
	LastName NVARCHAR(25) NOT NULL
)

CREATE PROC selectActors
AS
BEGIN
	SELECT * FROM Actor
END

CREATE TABLE Director
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	FirstName NVARCHAR(25) NOT NULL,
	LastName NVARCHAR(25) NOT NULL
)

CREATE TABLE MovieCast
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	MovieId INT FOREIGN KEY REFERENCES Movie(Id),
	ActorId INT FOREIGN KEY REFERENCES Actor(Id)
)

CREATE TABLE AppUser
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	UserName NVARCHAR(20) UNIQUE NOT NULL,
	UserPassword NVARCHAR(20) NOT NULL
)

CREATE TABLE AppAdmin
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	UserName NVARCHAR(20) UNIQUE NOT NULL,
	UserPassword NVARCHAR(20) NOT NULL
)