/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hr.alan.client;

import hr.alan.businessModel.Movie;
import hr.alan.businessModel.MovieArchive;
import hr.alan.dal.Repository;
import hr.alan.dal.RepositoryFactory;
import hr.alan.view.DragAndDropPanel;
import hr.alan.view.DragAndDropPanelDirectors;
import hr.alan.view.EditActorsPanel;
import hr.alan.view.EditDirectorsPanel;
import hr.alan.view.EditMoviesPanel;
import hr.algebra.utils.JAXBUtils;
import hr.algebra.utils.MessageUtils;
import hr.algebra.utils.PrepareArchiveUtils;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Alan
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    private static final String FILENAME = "moviearchive.xml";
    
    public MainForm() {
        initComponents();
        initPanels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpMainPane = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiSaveXml = new javax.swing.JMenuItem();
        jmiLogout = new javax.swing.JMenuItem();
        jmiExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiOpenMovies = new javax.swing.JMenuItem();
        jmiOpenDirectors = new javax.swing.JMenuItem();
        jmiOpenActors = new javax.swing.JMenuItem();
        jmiOpenDragDrop = new javax.swing.JMenuItem();
        jmiOpenDragDrop1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MOVIE APP");

        jMenu1.setText("Actions");

        jmiSaveXml.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jmiSaveXml.setText("Save XML");
        jmiSaveXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSaveXmlActionPerformed(evt);
            }
        });
        jMenu1.add(jmiSaveXml);

        jmiLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jmiLogout.setText("Logout");
        jmiLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jmiLogout);

        jmiExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmiExit.setText("Exit");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jMenu1.add(jmiExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Navigation");

        jmiOpenMovies.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        jmiOpenMovies.setText("Open movies");
        jmiOpenMovies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOpenMoviesActionPerformed(evt);
            }
        });
        jMenu2.add(jmiOpenMovies);

        jmiOpenDirectors.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        jmiOpenDirectors.setText("Open directors");
        jmiOpenDirectors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOpenDirectorsActionPerformed(evt);
            }
        });
        jMenu2.add(jmiOpenDirectors);

        jmiOpenActors.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_MASK));
        jmiOpenActors.setText("Open actors");
        jmiOpenActors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOpenActorsActionPerformed(evt);
            }
        });
        jMenu2.add(jmiOpenActors);

        jmiOpenDragDrop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_MASK));
        jmiOpenDragDrop.setText("Open drag and drop");
        jmiOpenDragDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOpenDragDropActionPerformed(evt);
            }
        });
        jMenu2.add(jmiOpenDragDrop);

        jmiOpenDragDrop1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_MASK));
        jmiOpenDragDrop1.setText("Open drag and drop bosses");
        jmiOpenDragDrop1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiOpenDragDrop1ActionPerformed(evt);
            }
        });
        jMenu2.add(jmiOpenDragDrop1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpMainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpMainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmiLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogoutActionPerformed
        this.dispose();
        LoginForm.main(null);
    }//GEN-LAST:event_jmiLogoutActionPerformed

    private void jmiOpenMoviesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOpenMoviesActionPerformed
        tpMainPane.setSelectedIndex(0);
    }//GEN-LAST:event_jmiOpenMoviesActionPerformed

    private void jmiOpenDirectorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOpenDirectorsActionPerformed
        tpMainPane.setSelectedIndex(1);
    }//GEN-LAST:event_jmiOpenDirectorsActionPerformed

    private void jmiOpenActorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOpenActorsActionPerformed
        tpMainPane.setSelectedIndex(2);
    }//GEN-LAST:event_jmiOpenActorsActionPerformed

    private void jmiOpenDragDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOpenDragDropActionPerformed
        tpMainPane.setSelectedIndex(3);
    }//GEN-LAST:event_jmiOpenDragDropActionPerformed

    private void jmiSaveXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSaveXmlActionPerformed
        MovieArchive archive;
        try {
            archive = PrepareArchiveUtils.prepareArchive();
            JAXBUtils.save(archive, FILENAME);
            MessageUtils.showInformationMessage("Success", "Movie Archive saved");
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jmiSaveXmlActionPerformed

    private void jmiOpenDragDrop1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiOpenDragDrop1ActionPerformed
        tpMainPane.setSelectedIndex(4);
    }//GEN-LAST:event_jmiOpenDragDrop1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainForm form = new MainForm();
                form.setExtendedState(JFrame.MAXIMIZED_BOTH);
                form.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiLogout;
    private javax.swing.JMenuItem jmiOpenActors;
    private javax.swing.JMenuItem jmiOpenDirectors;
    private javax.swing.JMenuItem jmiOpenDragDrop;
    private javax.swing.JMenuItem jmiOpenDragDrop1;
    private javax.swing.JMenuItem jmiOpenMovies;
    private javax.swing.JMenuItem jmiSaveXml;
    private javax.swing.JTabbedPane tpMainPane;
    // End of variables declaration//GEN-END:variables

    private void initPanels() {
        tpMainPane.add("MOVIES", new EditMoviesPanel());
        tpMainPane.add("DIRECTORS", new EditDirectorsPanel());
        tpMainPane.add("ACTORS", new EditActorsPanel());
        tpMainPane.add("DRAG N DROP ACTORS", new DragAndDropPanel());
        tpMainPane.add("DRAG N DROP BOSSES", new DragAndDropPanelDirectors());
    }
    
}
